modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "nocompassreequip"
version = "${version}"
displayName = "No Compass Reequip"
authors = "Noryea"
description = '''
Remove lodestone compass reequipping animation when it updates
'''

[[mixins]]
config = "nocompassreequip.mixins.json"

[[dependencies.nocompassreequip]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"

[[dependencies.nocompassreequip]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"