#

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
        
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup and Build with Gradle
      run: ./gradlew build

    - name: Setting mod version
      run: |
        cat $GITHUB_WORKSPACE/gradle.properties | grep ^archives_base_name= >> $GITHUB_ENV
        cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version= >> $GITHUB_ENV
        cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version= >> $GITHUB_ENV

    - name: Upload Build Artifact
      run: echo "package_name=[$minecraft_version multi-loader] $archives_base_name-$mod_version.${{ github.run_number }}" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.package_name }}
        path: |
          **/build/libs/
          !build/libs/
          !**/*-dev.jar
          !**/*-shadow.jar
          !**/*-transformProduction*.jar
          !**/testmod*/
